import ctypes

import numpy
from pyscf.dft.numint import NBINS, _dot_ao_ao_sparse, _scale_ao_sparse, xc_deriv

from ciderpress.dft.plans import libcider


def _r2vv10a(rho, coords, vvrho, vvweight, vvcoords, nlc_pars):
    C1, C2, C3, C4, C5 = nlc_pars
    thresh = 1e-8

    # output
    exc = numpy.zeros(rho[0, :].size)
    # vxc = numpy.zeros([2, rho[0, :].size])

    # outer grid needs threshing
    threshind = rho[0, :] >= thresh
    coords = coords[threshind]
    R = rho[0, :][threshind]
    Gx = rho[1, :][threshind]
    Gy = rho[2, :][threshind]
    Gz = rho[3, :][threshind]
    G = Gx**2.0 + Gy**2.0 + Gz**2.0

    # inner grid needs threshing
    innerthreshind = vvrho[0, :] >= thresh
    vvcoords = vvcoords[innerthreshind]
    vvweight = vvweight[innerthreshind]
    Rp = vvrho[0, :][innerthreshind]
    RpW = Rp * vvweight
    Gxp = vvrho[1, :][innerthreshind]
    Gyp = vvrho[2, :][innerthreshind]
    Gzp = vvrho[3, :][innerthreshind]
    Gp = Gxp**2.0 + Gyp**2.0 + Gzp**2.0

    # constants and parameters
    Pi = numpy.pi
    Pi43 = 4.0 * Pi / 3.0
    # Bvv, Cvv = nlc_pars
    Bvv = 1
    Bvv * 1.5 * Pi * ((9.0 * Pi) ** (-1.0 / 6.0))
    # Beta = ((3.0 / (Bvv * Bvv)) ** (0.75)) / 32.0

    # inner grid
    Wgp = C3 * Gp / (Rp * Rp)
    # Wsp = numpy.sqrt(Rp ** (2.0 / 3) + C2 * Wgp * Wgp)
    Wsp = Rp ** (1.0 / 3) + C2 * Wgp
    Mp = 1 + C1 / Wsp
    W0p = (Wgp * Wgp + Pi43 * Rp * Mp) ** 0.5
    Whp = Wsp / numpy.sqrt(C4 + C5 * W0p * W0p)
    # Whp = 0.1 * numpy.ones_like(W0p)
    # Whp = 1.0 / (Kvv * (Rp ** (1.0 / 6.0)))
    PRpW = Whp**1.5 * Mp * RpW
    Qp = W0p * Whp

    # outer grid
    Wg = C3 * G / (R * R)
    # Ws = numpy.sqrt(R ** (2.0 / 3) + C2 * Wg * Wg)
    Ws = R ** (1.0 / 3) + C2 * Wg
    M = 1 + C1 / Ws
    Wp2 = Pi43 * R * M
    W0 = (Wg * Wg + Wp2) ** 0.5
    Wh = Ws / numpy.sqrt(C4 + C5 * W0 * W0)
    # Wh = 0.1 * numpy.ones_like(W0)
    # Wh = 1.0 / (Kvv * (R ** (1.0 / 6.0)))
    P = Wh**1.5 * M
    Q = W0 * Wh
    # dW0dR = (0.5 * Pi43 * R - 2.0 * W0tmp) / W0
    # dW0dG = W0tmp * R / (G * W0)
    # dKdR = (1.0 / 6.0) * K

    vvcoords = numpy.asarray(vvcoords, order="C")
    coords = numpy.asarray(coords, order="C")
    F = numpy.empty_like(R)
    U = numpy.empty_like(R)
    W = numpy.empty_like(R)
    libcider.VXC_r2vv10a(
        F.ctypes.data_as(ctypes.c_void_p),
        U.ctypes.data_as(ctypes.c_void_p),
        W.ctypes.data_as(ctypes.c_void_p),
        vvcoords.ctypes.data_as(ctypes.c_void_p),
        coords.ctypes.data_as(ctypes.c_void_p),
        Qp.ctypes.data_as(ctypes.c_void_p),
        Q.ctypes.data_as(ctypes.c_void_p),
        PRpW.ctypes.data_as(ctypes.c_void_p),
        ctypes.c_int(vvcoords.shape[0]),
        ctypes.c_int(coords.shape[0]),
    )
    # exc is multiplied by Rho later
    exc[threshind] = 0.5 * F * P
    exc[threshind] += (3 * Wh**1.5 * Wp2**2) / (512 * R * W0**1.5)
    # vxc[0, threshind] = Beta + F + 1.5 * (U * dKdR + W * dW0dR)
    # vxc[1, threshind] = 1.5 * W * dW0dG
    return exc  # , vxc


def nr_nlc_vxc(
    ni, mol, grids, xc_code, dm, relativity=0, hermi=1, max_memory=2000, verbose=None
):
    """Calculate NLC functional and potential matrix on given grids

    Args:
        ni : an instance of :class:`NumInt`

        mol : an instance of :class:`Mole`

        grids : an instance of :class:`Grids`
            grids.coords and grids.weights are needed for coordinates and weights of meshgrids.
        xc_code : str
            XC functional description.
            See :func:`parse_xc` of pyscf/dft/libxc.py for more details.
        dm : 2D array
            Density matrix or multiple density matrices

    Kwargs:
        hermi : int
            Input density matrices symmetric or not. It also indicates whether
            the potential matrices in return are symmetric or not.
        max_memory : int or float
            The maximum size of cache to use (in MB).

    Returns:
        nelec, excsum, vmat.
        nelec is the number of electrons generated by numerical integration.
        excsum is the XC functional value.  vmat is the XC potential matrix in
        2D array of shape (nao,nao) where nao is the number of AO functions.
    """
    make_rho, nset, nao = ni._gen_rho_evaluator(mol, dm, hermi, False, grids)
    assert nset == 1
    ao_loc = mol.ao_loc_nr()
    cutoff = grids.cutoff * 1e2
    nbins = NBINS * 2 - int(NBINS * numpy.log(cutoff) / numpy.log(grids.cutoff))

    ao_deriv = 1
    vvrho = []
    for ao, mask, weight, coords in ni.block_loop(
        mol, grids, nao, ao_deriv, max_memory=max_memory
    ):
        vvrho.append(make_rho(0, ao, mask, "GGA"))
    rho = numpy.hstack(vvrho)

    exc = 0
    nlc_coefs = [([0.029, 0.01, 0.05, 40, 40], 1.0)]
    for nlc_pars, fac in nlc_coefs:
        e = _r2vv10a(rho, grids.coords, rho, grids.weights, grids.coords, nlc_pars)
        exc += e * fac
    den = rho[0] * grids.weights
    nelec = den.sum()
    excsum = numpy.dot(den, exc)
    return excsum
    vv_vxc = xc_deriv.transform_vxc(rho, vxc, "GGA", spin=0)

    pair_mask = mol.get_overlap_cond() < -numpy.log(ni.cutoff)
    aow = None
    vmat = numpy.zeros((nao, nao))
    p1 = 0
    for ao, mask, weight, coords in ni.block_loop(
        mol, grids, nao, ao_deriv, max_memory=max_memory
    ):
        p0, p1 = p1, p1 + weight.size
        wv = vv_vxc[:, p0:p1] * weight
        wv[0] *= 0.5
        aow = _scale_ao_sparse(ao[:4], wv[:4], mask, ao_loc, out=aow)
        _dot_ao_ao_sparse(
            ao[0], aow, None, nbins, mask, pair_mask, ao_loc, hermi=0, out=vmat
        )
    vmat = vmat + vmat.T
    return nelec, excsum, vmat
